MbmStore/Controllers/CartController.cs
using MbmStore.DAL;
using MbmStore.Models;
using MbmStore.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class CartController : Controller
    {
        private InvoiceRepository<Invoice> repo = new InvoiceRepository<Invoice>();

        // constructor
        // instantiale a new repository object
        public CartController()
        {
            repo = new InvoiceRepository<Invoice>();
        }


        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }


        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repo.GetProductById(productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { controller = returnUrl.Substring(1) });
        }


        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repo.GetProductById(productId);

            if (product != null)
            {
                cart.RemoveItem(product);
            }
            return RedirectToAction("Index", new { controller = returnUrl.Substring(1) });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                repo.SaveInvoice(cart, shippingDetails);
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

    }
}

MbmStore/Controllers/NavController.cs
using MbmStore.DAL;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class NavController : Controller
    {
        private MbmStoreContext db;

        public NavController()
        {
            db = new MbmStoreContext();
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = db.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

MbmStore/Views/Shared/ProductSummaryBook.cshtml
@model MbmStore.Models.Book

<div class="row">
    <div class="col-md-2">
        <img src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">
        <strong>Title:</strong> @Model.Title<br />
        <strong>Author:</strong> @Model.Author<br />
        <strong>Price:</strong> @Model.Price<br />
        <strong>Publisher:</strong> @Model.Publisher (@Model.Published)<br />
        <strong>ISBN:</strong> @Model.ISBN<br /> <br />
    </div>

    <div class="col-md-6">

        @using (Html.BeginForm("AddToCart", "Cart"))
            {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>
</div>

MbmStore/Views/Shared/ProductSummaryMovie.cshtml
@model MbmStore.Models.Movie

<div class="row">
    <div class="col-md-2">
        <img src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">
        <strong>Title:</strong> @Model.Title<br />
        <strong>Director:</strong> @Model.Director<br>
        <strong>Price:</strong> @String.Format("{0:0.00}", Model.Price) <br /><br />
    </div>
    <div class="col-md-6">

        @using (Html.BeginForm("AddToCart", "Cart"))
            {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>
</div>

MbmStore/Views/Shared/ProductSummaryMusicCD.cshtml
@using MbmStore.Models;
@model MbmStore.Models.MusicCD

<div class="row">
    <div class="col-md-2">
        <img src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">

        <strong>Album:</strong> @Model.Title<br />
        <strong>Artist:</strong> @Model.Artist<br />
        <strong>Price:</strong> @Model.Price<br />
        <strong>Publisher:</strong> @Model.Label (@Model.Released)<br /> <br />

    </div>

    <div class="col-md-6" style="vertical-align:bottom">

        @using (Html.BeginForm("AddToCart", "Cart"))
            {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>

    <div class="col-md-11">
        <strong>Tracks:</strong>
        <ul style="list-style:decimal; list-style-position:inside;">
            @foreach (Track track in Model.Tracks)
            {
                <li>@track.Title (@track.Composer) @track.Length.Minutes:@track.Length.Seconds.ToString("00")</li>
            }
        </ul>
        @if (Model.GetPlayingTime().Hours > 0)
        {
            <strong>Total playing time:</strong> @Model.GetPlayingTime().ToString(@"hh\:mm\:ss")
        }
        else
        {
            <strong>Total playing time:</strong> @Model.GetPlayingTime().ToString(@"mm\:ss");
        }
    </div>

</div>

MbmStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body class="container">
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Music Book Movie Store</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
           @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>